-- MySQL Script generated by MySQL Workbench
-- 2019年06月05日 星期三 16时50分21秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bank` (
  `Name` VARCHAR(10) NOT NULL,
  `City` VARCHAR(6) NOT NULL,
  `Fund` FLOAT NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `ID` CHAR(18) NOT NULL,
  `Name` VARCHAR(5) NOT NULL,
  `Is Manager` TINYINT NOT NULL,
  `Department` VARCHAR(10) NOT NULL,
  `Telephone` VARCHAR(15) NOT NULL,
  `Address` VARCHAR(30) NOT NULL,
  `Employed Date` DATE NOT NULL,
  `Manager ID` VARCHAR(18) NOT NULL,
  `Bank` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Staff_Bank1_idx` (`Bank` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Bank1`
    FOREIGN KEY (`Bank`)
    REFERENCES `mydb`.`Bank` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ID` CHAR(18) NOT NULL,
  `Name` VARCHAR(5) NOT NULL,
  `Telephone` VARCHAR(15) NOT NULL,
  `Address` VARCHAR(30) NOT NULL,
  `Contact Name` VARCHAR(5) NOT NULL,
  `Contact Telephone` VARCHAR(15) NOT NULL,
  `Contact Email` VARCHAR(20) NOT NULL,
  `Relationship with Contact` VARCHAR(6) NOT NULL,
  `Staff ID` CHAR(18) NULL,
  `Relationship with Staff` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Client_Staff1_idx` (`Staff ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Staff1`
    FOREIGN KEY (`Staff ID`)
    REFERENCES `mydb`.`Staff` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `Account ID` INT NOT NULL,
  `Client ID` CHAR(18) NOT NULL,
  `Type` TINYINT NOT NULL,
  `Balance` FLOAT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Bank` VARCHAR(10) NOT NULL,
  `Rate` FLOAT NULL,
  `Currency` VARCHAR(10) NULL,
  `Overdraft` FLOAT NULL,
  PRIMARY KEY (`Account ID`, `Type`, `Bank`),
  UNIQUE INDEX `ID_UNIQUE` (`Account ID` ASC) VISIBLE,
  INDEX `fk_Account_Bank1_idx` (`Bank` ASC) VISIBLE,
  INDEX `fk_Account_Client1_idx` (`Client ID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Bank1`
    FOREIGN KEY (`Bank`)
    REFERENCES `mydb`.`Bank` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Client1`
    FOREIGN KEY (`Client ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `Loan ID` INT NOT NULL,
  `Bank` VARCHAR(10) NOT NULL,
  `Loan` FLOAT NOT NULL,
  `Status` VARCHAR(4) NOT NULL,
  `Client ID` CHAR(18) NOT NULL,
  PRIMARY KEY (`Loan ID`, `Bank`),
  INDEX `fk_Loan_Bank1_idx` (`Bank` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`Loan ID` ASC) VISIBLE,
  INDEX `fk_Loan_Client1_idx` (`Client ID` ASC) VISIBLE,
  CONSTRAINT `fk_Loan_Bank1`
    FOREIGN KEY (`Bank`)
    REFERENCES `mydb`.`Bank` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_Client1`
    FOREIGN KEY (`Client ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LoanDistribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoanDistribution` (
  `Date` DATETIME NOT NULL,
  `Money` FLOAT NOT NULL,
  `Loan ID` INT NOT NULL,
  PRIMARY KEY (`Date`, `Loan ID`),
  INDEX `fk_LoanDistribution_Loan_idx` (`Loan ID` ASC) VISIBLE,
  CONSTRAINT `fk_LoanDistribution_Loan`
    FOREIGN KEY (`Loan ID`)
    REFERENCES `mydb`.`Loan` (`Loan ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_has_Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_has_Loan` (
  `ID` CHAR(18) NOT NULL,
  `Loan ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Loan ID`),
  INDEX `fk_Client_has_Loan_Loan1_idx` (`Loan ID` ASC) VISIBLE,
  INDEX `fk_Client_has_Loan_Client1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Loan_Client1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Loan_Loan1`
    FOREIGN KEY (`Loan ID`)
    REFERENCES `mydb`.`Loan` (`Loan ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_has_Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_has_Account` (
  `ID` CHAR(18) NOT NULL,
  `Account ID` INT NOT NULL,
  `Type` TINYINT NOT NULL,
  `Bank` VARCHAR(10) NOT NULL,
  `Recent Access Time` DATETIME NOT NULL,
  PRIMARY KEY (`ID`, `Account ID`, `Type`, `Bank`),
  INDEX `fk_Client_has_Account_Account1_idx` (`Account ID` ASC, `Type` ASC, `Bank` ASC) VISIBLE,
  INDEX `fk_Client_has_Account_Client1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Account_Client1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Account_Account1`
    FOREIGN KEY (`Account ID` , `Type` , `Bank`)
    REFERENCES `mydb`.`Account` (`Account ID` , `Type` , `Bank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
