-- MySQL Script generated by MySQL Workbench
-- 2019年06月10日 星期一 01时31分36秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app store` DEFAULT CHARACTER SET utf8 ;
USE `app store` ;

-- -----------------------------------------------------
-- Table `app store`.`Developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app store`.`Developer` (
  `ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app store`.`Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app store`.`Application` (
  `App ID` INT NOT NULL,
  `App Name` VARCHAR(10) NOT NULL,
  `Introduction` LONGTEXT NOT NULL,
  `Package` BLOB NOT NULL,
  `Developer ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`App ID`),
  INDEX `fk_Application_Developer1_idx` (`Developer ID` ASC) VISIBLE,
  CONSTRAINT `fk_Application_Developer1`
    FOREIGN KEY (`Developer ID`)
    REFERENCES `app store`.`Developer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app store`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app store`.`Client` (
  `ID` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app store`.`Client_has_Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app store`.`Client_has_Application` (
  `Client ID` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `App ID` INT NOT NULL,
  PRIMARY KEY (`Client ID`, `App ID`),
  INDEX `fk_Client_has_Application_Application1_idx` (`App ID` ASC) VISIBLE,
  INDEX `fk_Client_has_Application_Client_idx` (`Client ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Application_Client`
    FOREIGN KEY (`Client ID`)
    REFERENCES `app store`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Application_Application1`
    FOREIGN KEY (`App ID`)
    REFERENCES `app store`.`Application` (`App ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
